export const EMAILJS = {
  SERVICE_ID: import.meta.env.VITE_EMAILJS_SERVICE_ID,
  CONTACT_TEMPLATE: import.meta.env.VITE_EMAILJS_CONTACT_TEMPLATE,
  BOOKING_TEMPLATE: import.meta.env.VITE_EMAILJS_BOOKING_TEMPLATE,
  PUBLIC_KEY: import.meta.env.VITE_EMAILJS_PUBLIC_KEY,
};